### ISSUE TITLE
pointTo pointer transitions from outside colorbar

### ISSUE THREAD

**Issue by haroldsoh** [bmschmidt/colorbar#5]
The pointer transitions in from outside the colorbar (upon initialization) when the colorbar is horizontal. Is it possible to have pointer simply appear in place when it is not transitioning from another value?

**Comment by bmschmidt** [comment]
Ah, the pointer doesn't check if it's horizontal for the initial entry. Should be fixed now: https://github.com/bmschmidt/colorbar/commit/75f67ad35350f0c0faa56787e96f08049fe2d5c6
